path: /home/agil/Documents/Kuliah/IISMA/Ulsan College/UC Kuliah/Practical Cases In The IT Field/Projek besar/Training Segmentation/data
train: train
val: train

nc: 4
names: ['animal', 'misc', 'robot', 'vehicle']
